#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Gradle start up script for UNIX
# GENERATED by assistant: standard wrapper launcher
# ------------------------------------------------------------------------------
APP_HOME="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi

LAUNCHER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$LAUNCHER_JAR" ]; then
  echo "Gradle wrapper JAR not found in $APP_HOME/gradle/wrapper/"
  echo "Run 'gradle wrapper' (with system Gradle installed) to generate the wrapper files, or add the gradle-wrapper.jar to the repository."
  exit 1
fi

exec "$JAVA" -jar "$LAUNCHER_JAR" "$@"

