@echo off
rem ------------------------------------------------------------------------------
rem Gradle start up script for Windows
rem GENERATED by assistant: standard wrapper launcher
rem ------------------------------------------------------------------------------
setlocal
set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=

:findJavaFromJavaHome
if defined JAVA_HOME goto okFromJavaHome
set JAVA_HOME=%ProgramFiles%\Java\jdk-21
if defined JAVA_HOME goto okFromJavaHome
goto findFromPath

:okFromJavaHome
set JAVA_EXE=%JAVA_HOME%\bin\java.exe
if exist "%JAVA_EXE%" goto init

:findFromPath
set JAVA_EXE=java.exe

:init
set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
set LAUNCHER_JAR=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
if not exist "%LAUNCHER_JAR%" (
  echo Gradle wrapper JAR not found in %APP_HOME%\gradle\wrapper\
  echo Run "gradle wrapper" (with system Gradle installed) to generate the wrapper files, or add the gradle-wrapper.jar to the repository.
  exit /b 1
)

"%JAVA_EXE%" %DEFAULT_JVM_OPTS% -jar "%LAUNCHER_JAR%" %*

